services:
  frontend:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV:-development}
    container_name: ziro-frontend
    ports:
      - "5173:5173"
    env_file:
      - .env.${ENV:-local}
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "if [ '$NODE_ENV' = 'production' ];
              then yarn preview --port 5173 --host;
              else yarn dev --host 0.0.0.0;
              fi"
