version: "3.8"

services:
  frontend:
    build:
      context: .
      args:
        NODE_ENV: production # garante que o Dockerfile faça build em modo produção
    container_name: ziro-frontend
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: production
