services:
  frontend:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV:-development}
    container_name: ziro-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
