export enum AcaoButtonIcon {
  INCLUIR = "INCLUIR",
  ALTERAR = "ALTERAR",
  EXCLUIR = "EXCLUIR",
  CONFIGURAR = "CONFIGURAR",
  GRAFICO_BARRA = "GRAFICO_BARRA",
  GRAFICO_PIZZA = "GRAFICO_PIZZA",
  GRAFICO_LINHA = "GRAFICO_LINHA",
}
